services:
  - type: web
    name: lg-cluster-pricing-api
    env: python
    plan: free
    pythonVersion: 3.11.15   # explicitly tell Render the Python version
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
